### ISSUE TITLE
Out of bounds read in tinyobj::exportFaceGroupToShape

### ISSUE THREAD

**Issue by khang06** [syoyo/tinyobjloader#175]
```
$ ./test_loader '/home/khangaroo/afl/out/crashes/id:000000,sig:11,src:000000,op:havoc,rep:128' 
Loading /home/khangaroo/afl/out/crashes/id:000000,sig:11,src:000000,op:havoc,rep:128
ASAN:DEADLYSIGNAL
=================================================================
==10995==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000000c (pc 0x000000534ed2 bp 0x7ffdcc2e1760 sp 0x7ffdcc2e1240 T0)
==10995==The signal is caused by a READ memory access.
==10995==Hint: address points to the zero page.
    #0 0x534ed1 in tinyobj::exportFaceGroupToShape(tinyobj::shape_t*, std::vector<tinyobj::face_t, std::allocator<tinyobj::face_t> > const&, std::vector<tinyobj::tag_t, std::allocator<tinyobj::tag_t> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::vector<float, std::allocator<float> > const&) /home/khangaroo/github/tinyobjloader/tiny_obj_loader.h:1052:22
    #1 0x52f6b7 in tinyobj::LoadObj(tinyobj::attrib_t*, std::vector<tinyobj::shape_t, std::allocator<tinyobj::shape_t> >*, std::vector<tinyobj::material_t, std::allocator<tinyobj::material_t> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::istream*, tinyobj::MaterialReader*, bool) /home/khangaroo/github/tinyobjloader/tiny_obj_loader.h:2030:14
    #2 0x524c56 in tinyobj::LoadObj(tinyobj::attrib_t*, std::vector<tinyobj::shape_t, std::allocator<tinyobj::shape_t> >*, std::vector<tinyobj::material_t, std::allocator<tinyobj::material_t> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, char const*, bool) /home/khangaroo/github/tinyobjloader/tiny_obj_loader.h:1709:10
    #3 0x5443bd in TestLoadObj(char const*, char const*, bool) /home/khangaroo/github/tinyobjloader/loader_example.cc:292:14
    #4 0x541ba3 in main /home/khangaroo/github/tinyobjloader/loader_example.cc:426:25
    #5 0x7f4fad16ab96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #6 0x420659 in _start (/home/khangaroo/github/tinyobjloader/build/test_loader+0x420659)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/khangaroo/github/tinyobjloader/tiny_obj_loader.h:1052:22 in tinyobj::exportFaceGroupToShape(tinyobj::shape_t*, std::vector<tinyobj::face_t, std::allocator<tinyobj::face_t> > const&, std::vector<tinyobj::tag_t, std::allocator<tinyobj::tag_t> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::vector<float, std::allocator<float> > const&)
==10995==ABORTING
```
[crashes.zip](https://github.com/syoyo/tinyobjloader/files/2055637/crashes.zip)
so i decided to do a quick fuzzing run of tinyobjloader and i managed to find this vulnerability.
attached is my entire afl crashes folder. most of the crashes in it are this one bug but different addresses are read, but i haven't had the time to dissect every testcase to see what was different. it might be worth taking a look at.

**Comment by syoyo** [comment]
Thanks! I'll look into it soon!

**Comment by syoyo** [comment]
I have fixed all seg faults and out-of-bounds access in `afl` branch https://github.com/syoyo/tinyobjloader/tree/afl , and merged it to `master`

Thank you for reporting.

**Comment by khang06** [comment]
great! i did another fuzzing run and found no crashes.
i modified the test loader to load mtl files, but i also found no crashes there

**Comment by syoyo** [comment]
Good to know! > i modified the test loader to load mtl files, but i also found no crashes there
